// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bggctxetuyancrmxjqdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZ2N0eGV0dXlhbmNybXhqcWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MTA0MzcsImV4cCI6MjA1NzA4NjQzN30.pIl0dUvJCYgjLOQBBbX2dEkcrcT6vTBvdW217HJ87hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);